import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F0F4F8",
  },
  content: {
    padding: 20,
    paddingBottom: 48,
  },
  heading: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1B2A4A",
    marginBottom: 24,
  },
  label: {
    fontSize: 12,
    fontWeight: "600",
    color: "#888",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  dropdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  dropdownText: {
    fontSize: 15,
    color: "#1A1A2E",
    fontWeight: "500",
  },
  dropdownArrow: {
    fontSize: 16,
    color: "#888",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 60,
  },
  menu: {
    backgroundColor: "#fff",
    borderRadius: 14,
    overflow: "hidden",
    maxHeight: "70%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 10,
  },
  option: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F4F8",
  },
  optionSelected: {
    backgroundColor: "#EBF5FB",
  },
  optionText: {
    fontSize: 15,
    color: "#1A1A2E",
  },
  optionTextSelected: {
    fontWeight: "700",
    color: "#2E86C1",
  },
  button: {
    backgroundColor: "#1B2A4A",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 24,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  errorBox: {
    backgroundColor: "#FDEDEC",
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
  },
  errorText: {
    color: "#C0392B",
    fontSize: 14,
  },
  distanceCard: {
    backgroundColor: "#1B2A4A",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    marginBottom: 20,
  },
  distanceLabel: {
    color: "#94B4D0",
    fontSize: 13,
    marginBottom: 6,
  },
  distanceValue: {
    color: "#fff",
    fontSize: 48,
    fontWeight: "700",
    lineHeight: 52,
  },
  distanceUnit: {
    color: "#94B4D0",
    fontSize: 16,
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1A1A2E",
    marginBottom: 12,
    marginTop: 4,
  },
  placeRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  placeChip: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  placeName: {
    flex: 1,
    fontSize: 14,
    color: "#333",
  },
  placeHours: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1B2A4A",
  },
});
